name: Arecibo
favicon: null
layout_spectrum: 0.8725636841263622
typography_spectrum: 0.4732273251283914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41153302835300565
  lightness: 0.007818033453077078
  saturation: 0.9726040826644748
  rhythmicContrast: 0.8938623659778386
purpose: []
