name: Arecibo
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.73194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#87bbdb'
    - '#0a0000'
    - '#a18661'
    - '#fdde77'
    - '#8e050a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.9726040826644748
  rhythmicContrast: 0.8938623659778386
purpose: []
