name: Arecibo
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.73194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e2d3'
    - '#b48869'
    - '#523b30'
    - '#44799a'
    - '#d45245'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.9726040826644748
  rhythmicContrast: 0.25
purpose: []
